import { Head, router, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';

const types=['string','integer','decimal','boolean','json'];
export default function Index({organization,settings}:{organization:{name:string};settings:any[]}){
 const create=useForm({key:'',value:'',type:'string',group:'general',description:'',is_public:false,effective_from:new Date().toISOString().slice(0,10)});
 const submit=(e:FormEvent)=>{e.preventDefault();create.post('/admin/settings',{onSuccess:()=>create.reset()})};
 return <><Head title="System Settings"/><main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-6xl px-6 py-8"><a href="/admin" className="text-sm font-semibold text-emerald-700">← Dashboard</a><h1 className="mt-2 text-3xl font-bold">System Settings</h1><p className="text-slate-500">{organization.name} · configurable organization settings</p>
 <form onSubmit={submit} className="mt-6 grid gap-4 rounded-2xl border bg-white p-6 md:grid-cols-2"><h2 className="md:col-span-2 text-xl font-bold">Add setting</h2><input placeholder="Key e.g. contribution.monthly_minimum" value={create.data.key} onChange={e=>create.setData('key',e.target.value)} className="rounded-xl border px-4 py-3"/><input placeholder="Value" value={create.data.value} onChange={e=>create.setData('value',e.target.value)} className="rounded-xl border px-4 py-3"/>
 <select value={create.data.type} onChange={e=>create.setData('type',e.target.value)} className="rounded-xl border px-4 py-3">{types.map(t=><option key={t}>{t}</option>)}</select><input type="date" value={create.data.effective_from} onChange={e=>create.setData('effective_from',e.target.value)} className="rounded-xl border px-4 py-3"/><input type="date" value={create.data.effective_from} onChange={e=>create.setData('effective_from',e.target.value)} className="rounded-xl border px-4 py-3"/><input placeholder="Group" value={create.data.group} onChange={e=>create.setData('group',e.target.value)} className="rounded-xl border px-4 py-3"/><textarea placeholder="Description" value={create.data.description} onChange={e=>create.setData('description',e.target.value)} className="rounded-xl border px-4 py-3 md:col-span-2"/><label className="flex gap-2"><input type="checkbox" checked={create.data.is_public} onChange={e=>create.setData('is_public',e.target.checked)}/> Public setting</label><button disabled={create.processing} className="w-fit rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">Create setting</button></form>
 <div className="mt-6 space-y-4">{settings.map(s=><SettingRow key={s.id} setting={s}/>)}</div>
 </div></main></>
}
function SettingRow({setting}:{setting:any}){
 const f=useForm({value:setting.value||'',type:setting.type,group:setting.group,description:setting.description||'',is_public:setting.is_public,effective_from:''});
 return <form onSubmit={e=>{e.preventDefault();f.put(`/admin/settings/${setting.id}`)}} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-bold">{setting.key}</div><div className="text-sm text-slate-500">{setting.group} · {setting.type} · effective {setting.effective_from}</div></div><button type="button" onClick={()=>{if(confirm(`Remove ${setting.key}?`))router.delete(`/admin/settings/${setting.id}`)}} className="font-semibold text-red-600">Remove</button></div><div className="mt-4 grid gap-4 md:grid-cols-2"><input value={f.data.value} onChange={e=>f.setData('value',e.target.value)} className="rounded-xl border px-4 py-3"/><select value={f.data.type} onChange={e=>f.setData('type',e.target.value)} className="rounded-xl border px-4 py-3">{types.map(t=><option key={t}>{t}</option>)}</select><input type="date" value={f.data.effective_from} onChange={e=>f.setData('effective_from',e.target.value)} className="rounded-xl border px-4 py-3"/><input type="date" value={f.data.effective_from} onChange={e=>f.setData('effective_from',e.target.value)} className="rounded-xl border px-4 py-3"/><input value={f.data.group} onChange={e=>f.setData('group',e.target.value)} className="rounded-xl border px-4 py-3"/><label className="flex items-center gap-2"><input type="checkbox" checked={f.data.is_public} onChange={e=>f.setData('is_public',e.target.checked)}/> Public</label><textarea value={f.data.description} onChange={e=>f.setData('description',e.target.value)} className="rounded-xl border px-4 py-3 md:col-span-2"/><button disabled={f.processing} className="w-fit rounded-xl bg-slate-900 px-5 py-3 font-bold text-white">Save changes</button></div></form>
}