import { ArrowRight, CheckCircle2, HeartHandshake, Landmark, ShieldCheck, Users } from 'lucide-react';
import { Link } from '@inertiajs/react';
import PublicPageShell from '../Components/PublicPageShell';
import { usePublicData } from '../Components/usePublicData';

const fallback={image:'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=2200&q=88'};
const pillars=[['People first','Membership and participation stay at the centre of the experience.',Users],['Care with structure','Welfare support follows clear proposals, approvals, obligations, and records.',HeartHandshake],['Accountable leadership','Governance, elections, meetings, and decisions remain traceable.',Landmark],['Built for continuity','Institutional records can remain useful as people and leadership change.',ShieldCheck]];
export default function About(){const data=usePublicData('about',fallback);return <PublicPageShell eyebrow="About Ochoka Heritage" title={<>More than a platform. <span className="text-emerald-500">A community legacy.</span></>} intro="Ochoka Heritage is designed to give a community one trusted place for membership, welfare, contributions, governance, communication, and institutional memory." image={String(data.image)}>
<section className="mx-auto max-w-7xl px-5 pb-16 sm:px-6 lg:px-8 lg:pb-24"><div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-[2rem] border border-slate-200 bg-white p-7 shadow-sm sm:p-10"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-600">Why it exists</p><h2 className="mt-4 text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">Keep people connected and the institution organized.</h2><p className="mt-5 text-sm leading-7 text-slate-600 sm:text-base">Community organizations carry relationships, responsibilities, financial commitments, decisions, leadership history, and shared memories. The platform gives those moving parts a structured digital home without losing the human side of community.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Transparent records','Member-first experience','Structured workflows','Long-term continuity'].map(x=><div key={x} className="flex items-center gap-2.5 rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold text-slate-700"><CheckCircle2 size={17} className="text-emerald-500"/>{x}</div>)}</div></div><div className="rounded-[2rem] border border-emerald-100 bg-emerald-50/70 p-7 sm:p-10"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">Our direction</p><h2 className="mt-4 text-2xl font-black tracking-tight text-slate-950">A digital foundation for the community we want to preserve.</h2><p className="mt-4 text-sm leading-7 text-emerald-950/70">The system is intentionally modular and configurable so policies, leadership, contribution rules, welfare workflows, and public information can evolve without rewriting historical records.</p><Link href="/membership" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-extrabold text-white hover:bg-emerald-600">Explore membership <ArrowRight size={16}/></Link></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{pillars.map(([title,text,Icon])=>{const I=Icon as typeof Users;return <article key={title as string} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><I size={21}/></div><h3 className="mt-5 text-base font-black text-slate-950">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text as string}</p></article>})}</div></section></PublicPageShell>}
