import LegalPageLayout from '../Components/LegalPageLayout';

const sections = [
    { title: '1. Information we may handle', body: ['Depending on the features you use, Ochoka Heritage may handle information needed to manage membership, authentication, contributions, welfare, governance, elections, meetings, communications, documents, and related organizational records.', 'This may include account and profile information, membership information, transaction and contribution records, participation records, messages or notices, and information contained in documents submitted through the platform.'] },
    { title: '2. How information is used', body: ['Information is used to operate and administer the platform, maintain member records, support approved community workflows, process and reconcile recorded financial activity, administer welfare processes, support governance and elections, communicate organizational notices, and preserve institutional records.', 'Information may also be used for security, troubleshooting, auditing, service improvement, and compliance with applicable requirements.'] },
    { title: '3. Financial and welfare information', body: ['Contribution, payment, welfare, expense, and support records may be retained because they form part of the organization’s financial or institutional history.', 'Access to sensitive financial and welfare information should be restricted according to the permissions and responsibilities assigned to authorized users.'] },
    { title: '4. Governance and election information', body: ['Governance records, meeting records, nominations, election eligibility information, voting records, results, resolutions, and related audit information may be retained to support accountability and institutional continuity.', 'Election information may be subject to additional controls intended to protect ballot integrity and restrict access to information that should remain confidential.'] },
    { title: '5. Access and sharing', body: ['Access to information should be limited according to the user’s role, permissions, and the purpose for which the information is required.', 'Information may be disclosed where necessary to operate an authorized service, protect the platform, comply with a lawful requirement, or support an approved organizational process. Personal information should not be made publicly available merely because it exists in the platform.'] },
    { title: '6. Security and auditability', body: ['Reasonable technical and organizational measures are used to protect platform information against unauthorized access, alteration, loss, or misuse.', 'Important administrative and financial actions may be recorded in audit logs so that authorized administrators can investigate changes and maintain accountability.'] },
    { title: '7. Data retention', body: ['Some information may need to be retained after an account becomes inactive because it forms part of financial, governance, welfare, election, meeting, legal, or institutional records.', 'Retention periods and deletion practices may therefore differ depending on the type of information and the organization’s applicable rules.'] },
    { title: '8. Your responsibilities', body: ['You should keep your account credentials secure, provide accurate information, avoid sharing information with unauthorized people, and promptly report suspected unauthorized access or misuse.'] },
    { title: '9. Changes to this privacy notice', body: ['This privacy notice may be updated when the platform, organizational processes, service providers, or applicable requirements change. The version published on this page is the version applicable from its stated effective date.'] },
    { title: '10. Questions about privacy', body: ['Questions or concerns about personal information and privacy should be raised through the organization’s designated communication channels so that they can be handled by the appropriate authorized person.'] },
];

export default function Privacy() {
    return <LegalPageLayout title="Privacy Notice" intro="How information may be handled, protected, retained, and used across the Ochoka Heritage platform." effectiveDate="September 13, 2026" icon="privacy" sections={sections} image="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=2200&q=85" />;
}
