import LegalPageLayout from '../Components/LegalPageLayout';

const sections = [
    { title: '1. Acceptance of these terms', body: ['By accessing or using the Ochoka Heritage platform, you agree to use it responsibly and in accordance with applicable organizational rules, permissions, and applicable law.', 'These terms describe general platform use. They do not replace the constitution, approved policies, resolutions, financial rules, election rules, welfare rules, or other governing instruments of the organization.'] },
    { title: '2. Member and user accounts', body: ['Users are responsible for providing accurate information and keeping their authentication credentials secure.', 'Access to administrative or executive functions is permission-based. Holding an organizational role does not remove a person’s responsibilities as a member or user of the platform.'] },
    { title: '3. Acceptable use', body: ['The platform must be used for legitimate community, organizational, administrative, governance, financial, welfare, communication, and related purposes.', 'Users must not attempt to gain unauthorized access, interfere with platform operation, misuse another person’s information, falsify records, or use the platform for unlawful or abusive activity.'] },
    { title: '4. Community records', body: ['The platform may contain membership, welfare, contribution, payment, meeting, election, governance, document, and communication records.', 'Users should understand that some records are institutional records and may be retained for accountability, auditability, continuity, and historical purposes even when an individual account later becomes inactive.'] },
    { title: '5. Financial and welfare workflows', body: ['Financial records, contribution obligations, payments, welfare proposals, approvals, support obligations, and related records are governed by the organization’s approved rules and workflows.', 'Recording information in the platform does not by itself create an approval, payment, welfare entitlement, or financial obligation unless the applicable workflow or authorized decision provides for it.'] },
    { title: '6. Elections and governance', body: ['Election and governance features are subject to the organization’s approved rules, eligibility requirements, nomination procedures, voting procedures, and authorized decisions.', 'Where the platform records a completed governance action, the relevant record may be retained for accountability and institutional continuity.'] },
    { title: '7. Platform availability', body: ['The platform may occasionally be unavailable because of maintenance, upgrades, technical failures, connectivity issues, or circumstances outside the immediate control of the organization.', 'Reasonable measures may be taken to preserve data integrity and service continuity, but uninterrupted availability cannot be guaranteed.'] },
    { title: '8. Intellectual property', body: ['The platform’s software, interface, branding, documentation, and other protected materials belong to their respective owners unless otherwise stated. Protected components may not be copied, modified, redistributed, reverse engineered, or commercially exploited without appropriate authorization.'] },
    { title: '9. Changes to these terms', body: ['These terms may be updated when the platform, organizational procedures, or applicable requirements change. The version published on this page is the version applicable from its stated effective date.'] },
    { title: '10. Contact and questions', body: ['Questions about these terms, membership responsibilities, or use of the platform should be directed through the organization’s designated communication channels.'] },
];

export default function Terms() {
    return <LegalPageLayout title="Terms of Use" intro="The rules and responsibilities that guide responsible use of the Ochoka Heritage community platform." effectiveDate="September 13, 2026" icon="terms" sections={sections} image="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=2200&q=85" />;
}
