import { Head, Link, useForm } from '@inertiajs/react';
export default function Create({organization,members,positions}:{organization:{name:string};members:any[];positions:any[]}){
 const f=useForm({member_id:'',executive_position_id:'',starts_at:'',ends_at:'',reason:''});
 return <><Head title="Appoint Executive"/><main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-3xl px-6 py-8"><Link href="/admin/governance/appointments" className="text-sm font-semibold text-emerald-700">← Appointments</Link><h1 className="mt-2 text-3xl font-bold">Appoint Executive</h1><p className="text-slate-500">{organization.name}</p><form onSubmit={e=>{e.preventDefault();f.post('/admin/governance/appointments')}} className="mt-6 space-y-5 rounded-2xl border bg-white p-6">
 <div><label className="block text-sm font-semibold">Member *</label><select value={f.data.member_id} onChange={e=>f.setData('member_id',e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"><option value="">Select member</option>{members.map(m=><option key={m.id} value={m.id}>{[m.first_name,m.middle_name,m.last_name].filter(Boolean).join(' ')} — {m.membership_number}</option>)}</select>{f.errors.member_id&&<p className="text-sm text-red-600">{f.errors.member_id}</p>}</div>
 <div><label className="block text-sm font-semibold">Position *</label><select value={f.data.executive_position_id} onChange={e=>f.setData('executive_position_id',e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"><option value="">Select position</option>{positions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{f.errors.executive_position_id&&<p className="text-sm text-red-600">{f.errors.executive_position_id}</p>}</div>
 <div className="grid gap-5 md:grid-cols-2"><div><label className="block text-sm font-semibold">Start date *</label><input type="date" value={f.data.starts_at} onChange={e=>f.setData('starts_at',e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/></div><div><label className="block text-sm font-semibold">End date</label><input type="date" value={f.data.ends_at} onChange={e=>f.setData('ends_at',e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/></div></div>
 <div><label className="block text-sm font-semibold">Reason</label><textarea value={f.data.reason} onChange={e=>f.setData('reason',e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/></div><button disabled={f.processing} className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">Create appointment</button>
 </form></div></main></>
}